branches:
  only:
  - master
  - devel

env:
  global:
  - RGL_USE_NULL=TRUE
  - PKG_CFLAGS="-O3 -Wall -pedantic"

language: r
sudo: required
cache: packages

cran: "http://cran.rstudio.com"
warnings_are_errors: true
r_build_args: ''
r_check_args: '--no-build-vignettes'

r:
  - oldrel
  - release
  - devel

#before_install:
  #- Rscript -e 'update.packages(ask = FALSE)'

addons:
  apt:
    packages:
      - libnlopt-dev

r_packages:
  - devtools
  - covr

r_github_packages:
  - jimhester/covr
  - r-lib/devtools
  - r-lib/sessioninfo
  - RDatatable/data.table
  - osofr/simcausal
  - osofr/condensier
  - tlverse/delayed
  - tlverse/origami
  - tlverse/sl3

after_success:
  - travis_wait 80 Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

